# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - CGO_ENABLED=0
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

    # We strongly recommend running tests to catch any regression before release. 
    # Even though, this an optional step.
    - go test ./...
    
    # If you need to release binaries compatible with a previous version, please update the "latest" tag with that version 
    # to properly check the compatibility.
    - go get github.com/hashicorp/packer@latest 

    # You may remove this if you generate these on your own
    - go install github.com/hashicorp/packer/cmd/mapstructure-to-hcl2
    - go generate ./...

    # Install packer-plugin-check to check binary compatibility with Packer
    - go install github.com/hashicorp/packer/cmd/packer-plugin-check

builds:
  # A separated build to run the packer-plugin-check only once for a linux_amd64 binary
  -
    id: plugin-check
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        # This will check plugin compatibility by making sure packer can load the binary
        - cmd: packer-plugin-check -load={{ .Name }}
          dir: "{{ dir .Path}}"
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'  ## can be useful to set variables 
    goos:
      - linux
    goarch:
      - amd64
    binary: '{{ .ProjectName }}_{{ .Version }}'
  - 
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'  ## can be useful to set variables 
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: linux
        goarch: amd64
    binary: '{{ .ProjectName }}_{{ .Version }}'
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      # if you are using this is in a GitHub action or some other automated pipeline, you 
      # need to pass the batch flag to indicate its not interactive.
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true
changelog:
  skip: true
