name: test packer-github-action

on:
  workflow_dispatch:
    inputs:
      logs:
        description: 'Set 1 to activate full logs'
        required: false
        default: '0'
      folder:
        description: 'Example folder'
        required: false
        default: './example'
      packerVersion:
        description: 'Packer version'
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    name: init and build example
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Init
        uses: hashicorp/packer-github-actions@document_logs
        with:
          working_directory: ${{ github.event.inputs.folder }}
          command: init
          target: .

      - name: Validate
        uses: hashicorp/packer-github-actions@document_logs
        with:
          working_directory: ${{ github.event.inputs.folder }}
          command: validate
          target: .
        env:
          PACKER_LOG: 1

      - name: Build
        uses: hashicorp/packer-github-actions@document_logs
        with:
          working_directory: ${{ github.event.inputs.folder }}
          command: build
          target: .
        env:
          PACKER_LOG: 1